In [1]:
# https://archive.ics.uci.edu/dataset/53/iris

In [2]:
import pandas as pd

In [3]:
file_path = "Resources/iris.csv"
iris_df = pd.read_csv(file_path)
iris_df.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
# drop class field
new_iris_df = iris_df.drop(["class"],axis=1)
new_iris_df

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [6]:
new_iris_df = new_iris_df[["sepal_length","petal_length","sepal_width","petal_width"]]
new_iris_df

     sepal_length  petal_length  sepal_width  petal_width
0             5.1           1.4          3.5          0.2
1             4.9           1.4          3.0          0.2
2             4.7           1.3          3.2          0.2
3             4.6           1.5          3.1          0.2
4             5.0           1.4          3.6          0.2
..            ...           ...          ...          ...
145           6.7           5.2          3.0          2.3
146           6.3           5.0          2.5          1.9
147           6.5           5.2          3.0          2.0
148           6.2           5.4          3.4          2.3
149           5.9           5.1          3.0          1.8

[150 rows x 4 columns]

In [7]:
# Cleaning this dataset appears complete with all the data in numerical form and the same type, so no data processing is needed. However, you'll encounter data transformations on datasets that contain categorical data or non-numeric features (e.g., transforming male and female categorical values to 0 and 1, respectively).

# Finally, the preprocessed DataFrame is saved on a new CSV file for future use. This is done by storing the file path in a variable, then using the Pandas to_csv() method to export the DataFrame to a CSV by supplying the file path and file name as arguments, as shown below:

output_file_path = "Resources/new_iris_data.csv"
new_iris_df.to_csv(output_file_path, index=False)