In [2]:
import pandas as pd

In [3]:
#Load Data
file_path = "Resources/shopping_data.csv"
df_shopping = pd.read_csv(file_path)
df_shopping.head()

   CustomerID Card Member   Age  Annual Income  Spending Score (1-100)
0           1         Yes  19.0          15000                    39.0
1           2         Yes  21.0          15000                    81.0
2           3          No  20.0          16000                     6.0
3           4          No  23.0          16000                    77.0
4           5          No  31.0          17000                    40.0

In [4]:
# What knowledge do we hope to glean from running an unsupervised learning model on this dataset?
# What data is available? What type? What is missing? What can be removed?
# Is the data in a format that can be passed into an unsupervised learning model?
# Can I quickly hand off this data for others to use?

In [5]:
# Columns
df_shopping.columns

Index(['CustomerID', 'Card Member', 'Age', 'Annual Income',
       'Spending Score (1-100)'],
      dtype='object')

In [6]:
# dataframe column types
df_shopping.dtypes

CustomerID                  int64
Card Member                object
Age                       float64
Annual Income               int64
Spending Score (1-100)    float64
dtype: object

In [7]:
# if missing data
# ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [8]:
# For example, return to our Age and Income groups: If it turns out there are 1,200 rows without any Age data points, then we clearly can't use that column in our model. There is no set cutoff for missing data—that decision is left up to you, the analyst, and must be made based on your understanding of the business needs.

In [9]:
# find null values
for column in df_shopping.columns:
    print(f"Column {column} has {df_shopping[column].isnull().sum()} null values")

Column CustomerID has 0 null values
Column Card Member has 2 null values
Column Age has 2 null values
Column Annual Income has 0 null values
Column Spending Score (1-100) has 1 null values

In [11]:
# There will be a few rows with missing values that we'll need to handle. The judgement call will be to either remove these rows or decide that the dataset is not suitable for our model. In this case, we'll proceed with handling these values because they are a small percentage of the overall data.

# What can be removed?

# You have begun to explore the data and have taken a look at null values. Next, determine if the data can be removed. Consider: Are there string columns that we can't use? Are there columns with excessive null data points? Was our decision to handle missing values to just remove them?

# In our example, there are no string type columns, and we made the decision that only a few rows have null data points, but not enough to remove a whole column's worth.

# Rows of data with null values can be removed with the dropna() method, as shown below:

# Drop null rows
df_shopping = df_shopping.dropna()

In [12]:
# remove duplicates
print(f"Duplicate entries: {df_shopping.duplicated().sum()}")

Duplicate entries: 0

In [13]:
# To remove the customer ID column, just enter the code below:
df_shopping.drop(columns=["CustomerID"], inplace=True)
df_shopping.head()

  Card Member   Age  Annual Income  Spending Score (1-100)
0         Yes  19.0          15000                    39.0
1         Yes  21.0          15000                    81.0
2          No  20.0          16000                     6.0
3          No  23.0          16000                    77.0
4          No  31.0          17000                    40.0

In [14]:
# Null values are handled.
# Only numerical data is used.
# Values are scaled. In other words, data has been manipulated to ensure that the variance between the numbers won't skew results.

In [15]:
# Is the data in a format that can be passed into an unsupervised learning model?

# We saw before that all our data had the correct type for each column; however, we know that our model can't have strings passed into it.

# To make sure we can use our string data, we'll transform our strings of Yes and No from the Card Member column to 1 and 0, respectively, by creating a function that will convert Yes to a 1 and anything else to 0.

# The function will then be run on the whole column with the .apply method, as shown below:

In [16]:
def change_string(member):
    if member == "Yes":
        return 1
    else:
        return 0
    
df_shopping["Card Member"] = df_shopping["Card Member"].apply(change_string)
df_shopping.head()

   Card Member   Age  Annual Income  Spending Score (1-100)
0            1  19.0          15000                    39.0
1            1  21.0          15000                    81.0
2            0  20.0          16000                     6.0
3            0  23.0          16000                    77.0
4            0  31.0          17000                    40.0

In [17]:
# he scale for Annual Income is much larger than all the other values in the dataset. We can adjust this format by dividing by 1,000 to rescale those data points, as shown below:

In [18]:
df_shopping["Annual Income"] = df_shopping["Annual Income"]/1000
df_shopping

     Card Member   Age  Annual Income  Spending Score (1-100)
0              1  19.0           15.0                    39.0
1              1  21.0           15.0                    81.0
2              0  20.0           16.0                     6.0
3              0  23.0           16.0                    77.0
4              0  31.0           17.0                    40.0
..           ...   ...            ...                     ...
198            0  35.0          120.0                    79.0
199            0  45.0          126.0                    28.0
200            1  32.0          126.0                    74.0
201            1  32.0          137.0                    18.0
202            1  30.0          137.0                    83.0

[200 rows x 4 columns]

In [19]:
# Reformat the names of the columns so they contain no spaces or numbers.

In [20]:
# Or rename the existing DataFrame (rather than creating a copy) 
df_shopping.rename(columns={'Card Member': 'card_member', 'Age': 'age', 'Annual Income': 'annual_income_scaled', 'Spending Score (1-100)': 'spending_score'}, inplace=True) 
df_shopping

     card_member   age  annual_income_scaled  spending_score
0              1  19.0                  15.0            39.0
1              1  21.0                  15.0            81.0
2              0  20.0                  16.0             6.0
3              0  23.0                  16.0            77.0
4              0  31.0                  17.0            40.0
..           ...   ...                   ...             ...
198            0  35.0                 120.0            79.0
199            0  45.0                 126.0            28.0
200            1  32.0                 126.0            74.0
201            1  32.0                 137.0            18.0
202            1  30.0                 137.0            83.0

[200 rows x 4 columns]

In [21]:
# Saving cleaned data
file_path = "Resources/shopping_data_cleaned.csv"
df_shopping.to_csv(file_path, index=False)

In [23]:
# duff format
# Saving cleaned data
file_path = "Resources/shopping_data_cleaned.xlsx"
df_shopping.to_excel(file_path, index=False)